# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f4f3f61b-8992-4aa7-951e-e0d27fa36172";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:3" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f4f3f61b-8992-4aa7-951e-e0d27fa36172";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" "compress=zstd:3" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f4f3f61b-8992-4aa7-951e-e0d27fa36172";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "compress=zstd:3" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/742D-00F3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d171a4fb-d14b-40cb-9100-d188db034ef6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
